export const SOKUON_SPELLINGS = ["xtu", "ltu", "xtsu", "ltsu"] as const;

export const HATSUON_SPELLINGS = ["nn", "n'", "xn"] as const;

export const MONOGRAPHS: Readonly<Record<string, readonly string[]>> = {
  あ: ["a"],
  い: ["i", "yi"],
  う: ["u", "wu", "whu"],
  え: ["e"],
  お: ["o"],
  か: ["ka", "ca"],
  き: ["ki"],
  く: ["ku", "cu", "qu"],
  け: ["ke"],
  こ: ["ko", "co"],
  が: ["ga"],
  ぎ: ["gi"],
  ぐ: ["gu"],
  げ: ["ge"],
  ご: ["go"],
  さ: ["sa"],
  し: ["si", "shi", "ci"],
  す: ["su"],
  せ: ["se", "ce"],
  そ: ["so"],
  ざ: ["za"],
  じ: ["zi", "ji"],
  ず: ["zu"],
  ぜ: ["ze"],
  ぞ: ["zo"],
  た: ["ta"],
  ち: ["ti", "chi"],
  つ: ["tu", "tsu"],
  て: ["te"],
  と: ["to"],
  だ: ["da"],
  ぢ: ["di"],
  づ: ["du"],
  で: ["de"],
  ど: ["do"],
  な: ["na"],
  に: ["ni"],
  ぬ: ["nu"],
  ね: ["ne"],
  の: ["no"],
  は: ["ha"],
  ひ: ["hi"],
  ふ: ["hu", "fu"],
  へ: ["he"],
  ほ: ["ho"],
  ば: ["ba"],
  び: ["bi"],
  ぶ: ["bu"],
  べ: ["be"],
  ぼ: ["bo"],
  ぱ: ["pa"],
  ぴ: ["pi"],
  ぷ: ["pu"],
  ぺ: ["pe"],
  ぽ: ["po"],
  ま: ["ma"],
  み: ["mi"],
  む: ["mu"],
  め: ["me"],
  も: ["mo"],
  や: ["ya"],
  ゆ: ["yu"],
  よ: ["yo"],
  ら: ["ra"],
  り: ["ri"],
  る: ["ru"],
  れ: ["re"],
  ろ: ["ro"],
  わ: ["wa"],
  ゐ: ["wi"],
  ゑ: ["we"],
  を: ["wo"],
  ゔ: ["vu"],
  ん: HATSUON_SPELLINGS,
  っ: SOKUON_SPELLINGS,
  ぁ: ["xa", "la"],
  ぃ: ["xi", "li"],
  ぅ: ["xu", "lu"],
  ぇ: ["xe", "le"],
  ぉ: ["xo", "lo"],
  ゃ: ["xya", "lya"],
  ゅ: ["xyu", "lyu"],
  ょ: ["xyo", "lyo"],
  ゎ: ["xwa", "lwa"],
  ゕ: ["xka", "lka"],
  ゖ: ["xke", "lke"],
};

export const DIGRAPHS: Readonly<Record<string, readonly string[]>> = {
  きゃ: ["kya"],
  きぃ: ["kyi"],
  きゅ: ["kyu"],
  きぇ: ["kye"],
  きょ: ["kyo"],
  ぎゃ: ["gya"],
  ぎぃ: ["gyi"],
  ぎゅ: ["gyu"],
  ぎぇ: ["gye"],
  ぎょ: ["gyo"],
  しゃ: ["sya", "sha"],
  しぃ: ["syi"],
  しゅ: ["syu", "shu"],
  しぇ: ["sye", "she"],
  しょ: ["syo", "sho"],
  じゃ: ["ja", "zya", "jya"],
  じぃ: ["zyi", "jyi"],
  じゅ: ["ju", "zyu", "jyu"],
  じぇ: ["je", "zye", "jye"],
  じょ: ["jo", "zyo", "jyo"],
  ちゃ: ["tya", "cha", "cya"],
  ちぃ: ["tyi", "cyi"],
  ちゅ: ["tyu", "chu", "cyu"],
  ちぇ: ["tye", "che", "cye"],
  ちょ: ["tyo", "cho", "cyo"],
  ぢゃ: ["dya"],
  ぢぃ: ["dyi"],
  ぢゅ: ["dyu"],
  ぢぇ: ["dye"],
  ぢょ: ["dyo"],
  にゃ: ["nya"],
  にぃ: ["nyi"],
  にゅ: ["nyu"],
  にぇ: ["nye"],
  にょ: ["nyo"],
  ひゃ: ["hya"],
  ひぃ: ["hyi"],
  ひゅ: ["hyu"],
  ひぇ: ["hye"],
  ひょ: ["hyo"],
  びゃ: ["bya"],
  びぃ: ["byi"],
  びゅ: ["byu"],
  びぇ: ["bye"],
  びょ: ["byo"],
  ぴゃ: ["pya"],
  ぴぃ: ["pyi"],
  ぴゅ: ["pyu"],
  ぴぇ: ["pye"],
  ぴょ: ["pyo"],
  みゃ: ["mya"],
  みぃ: ["myi"],
  みゅ: ["myu"],
  みぇ: ["mye"],
  みょ: ["myo"],
  りゃ: ["rya"],
  りぃ: ["ryi"],
  りゅ: ["ryu"],
  りぇ: ["rye"],
  りょ: ["ryo"],
  ふぁ: ["fa", "fwa"],
  ふぃ: ["fi", "fwi"],
  ふぅ: ["fwu"],
  ふぇ: ["fe", "fwe"],
  ふぉ: ["fo", "fwo"],
  ふゃ: ["fya"],
  ふゅ: ["fyu"],
  ふょ: ["fyo"],
  ゔぁ: ["va"],
  ゔぃ: ["vi", "vyi"],
  ゔぇ: ["ve", "vye"],
  ゔぉ: ["vo"],
  ゔゃ: ["vya"],
  ゔゅ: ["vyu"],
  ゔょ: ["vyo"],
  うぁ: ["wha"],
  うぃ: ["wi", "whi"],
  うぇ: ["we", "whe"],
  うぉ: ["who"],
  てぁ: ["tha"],
  てぃ: ["thi"],
  てゅ: ["thu"],
  てぇ: ["the"],
  てょ: ["tho"],
  でぁ: ["dha"],
  でぃ: ["dhi"],
  でゅ: ["dhu"],
  でぇ: ["dhe"],
  でょ: ["dho"],
  とぁ: ["twa"],
  とぃ: ["twi"],
  とぅ: ["twu"],
  とぇ: ["twe"],
  とぉ: ["two"],
  どぁ: ["dwa"],
  どぃ: ["dwi"],
  どぅ: ["dwu"],
  どぇ: ["dwe"],
  どぉ: ["dwo"],
  くぁ: ["qa", "kwa"],
  くぃ: ["qi", "kwi"],
  くぅ: ["qwu", "kwu"],
  くぇ: ["qe", "kwe"],
  くぉ: ["qo", "kwo"],
  ぐぁ: ["gwa"],
  ぐぃ: ["gwi"],
  ぐぅ: ["gwu"],
  ぐぇ: ["gwe"],
  ぐぉ: ["gwo"],
  すぁ: ["swa"],
  すぃ: ["swi"],
  すぅ: ["swu"],
  すぇ: ["swe"],
  すぉ: ["swo"],
  つぁ: ["tsa"],
  つぃ: ["tsi"],
  つぇ: ["tse"],
  つぉ: ["tso"],
  いぇ: ["ye"],
};

export const PUNCTUATION: Readonly<Record<string, readonly string[]>> = {
  ー: ["-"],
  "、": [","],
  "。": ["."],
  "・": ["/"],
  "「": ["["],
  "」": ["]"],
  "〜": ["~"],
  "　": [" "],
};

export const DOUBLABLE = /^[bcdfghjkmpqrstvwyz]/;

export const ABSORBS_SINGLE_N = /^[aiueony]/;

const KATAKANA_FIRST = 0x30a1;
const KATAKANA_LAST = 0x30f6;
const KATAKANA_TO_HIRAGANA = -0x60;
const FULLWIDTH_FIRST = 0xff01;
const FULLWIDTH_LAST = 0xff5e;
const FULLWIDTH_TO_HALFWIDTH = -0xfee0;

export function normalize(source: string): string {
  let normalized = "";
  for (const char of source) {
    const code = char.codePointAt(0)!;
    if (code >= KATAKANA_FIRST && code <= KATAKANA_LAST) {
      normalized += String.fromCodePoint(code + KATAKANA_TO_HIRAGANA);
    } else if (code >= FULLWIDTH_FIRST && code <= FULLWIDTH_LAST) {
      normalized += String.fromCodePoint(code + FULLWIDTH_TO_HALFWIDTH);
    } else {
      normalized += char;
    }
  }
  return normalized;
}

export function orderCandidates(candidates: readonly string[]): string[] {
  return [...new Set(candidates)].sort((a, b) => a.length - b.length);
}
